version: '3'

services:

  nginx:
    container_name: de_webserver
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    container_name: de_app
    build: php
    volumes:
      - ../source:/app